# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.default_vat_rate: 20.0

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'
            float $defaultVatRate: '%app.default_vat_rate%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # On ajoute un tag à tous les clients qui implémentent l'interface LlmClientInterface
    _instanceof:
        App\Llm\LlmClientInterface:
            tags: [ 'app.llm_client' ]

    # On configure la Factory avec les variables déclarées dans le .env
    App\Llm\LlmClientFactory:
        arguments:
            $defaultProvider: '%env(default::LLM_PROVIDER)%'
            $defaultModel: '%env(default::LLM_MODEL)%'

    # Configuration spécifique pour le client OpenRouter
    App\Llm\OpenRouterClient:
        public: true
        arguments:
            # Client http configuré dans config/packages/framework.yaml
            $openRouterClient: '@openrouter.client'

    # Configuration spécifique pour le client Google/Gemini
    App\Llm\GeminiClient:
        public: true
        arguments:
            $httpClient: '@gemini.client'
            $apiKey: '%env(default::GEMINI_API_KEY)%'

    # Configuration spécifique pour le client Ollama
    App\Llm\OllamaClient:
        public: true

    # Configuration spécifique pour le service Ollama
    App\Service\OllamaService:
        public: true
        arguments:
            $ollamaHost: '%env(default::OLLAMA_HOST)%'
