# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.default_vat_rate: 20.0

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $model: '%env(MODEL)%'
            string $projectDir: '%kernel.project_dir%'
            string $ollamaApiUrl: '%env(OLLAMA_API_URL)%'
            float $defaultVatRate: '%app.default_vat_rate%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration spécifique pour le client OpenRouter
    App\Llm\OpenRouterClient:
        public: true
        arguments:
            $openRouterClient: '@openrouter.client'

    # Configuration spécifique pour le client Ollama
    App\Llm\OllamaClient:
        public: true

    # On utilise le container pour récupérer le bon service au runtime
    App\Llm\LlmClientInterface:
        factory: ['@service_container', 'get']
        arguments:
            - '%env(resolve:LLM_PROVIDER_SERVICE)%'

    App\Service\TestGenerator: ~
